name: Continuous Integration
on:
    release:
    push: 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                version: latest
            - uses: actions/checkout@v4
            - name: Install NPM Dependencies
              run: pnpm i
            - name: Build
              run: npm run build
            - uses: actions/upload-artifact@v4
              with:
                name: build
                path: build

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup SSH Agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{env.DEPLOY_PRIVATE_KEY}}
            - uses: actions/download-artifact@v4
              with:
                name: build
            - name: Transfer artifact to target
              run: scp -r build/* ${{env.DEPLOY_SSH_URL}}